# Generated by Django 4.2.3 on 2023-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('urlpath', models.CharField(max_length=1000)),
                ('fontpath', models.CharField(max_length=1000)),
            ],
        ),
    ]
